### PR TITLE
fix(edit): fix unallowed user access

### LINKED ISSUE #105: Fix user edit in url access

### PR DESCRIPTION
**Pull request by chenyair**
closes #105

### CODE REVIEW

File: frontend/src/pages/experiences/experience-dialog/components/experience-dialog.tsx [hunk 1]
```diff
@@ -41,19 +41,25 @@ const ExperienceDialog = ({ mode = 'new' }: ExperienceDialogProps) => {
     enabled: mode === 'edit',
   });
 
+  useEffect(() => {
+    if (status === 'success' && experience!.userId.toString() !== user?._id) {
+      navigate({ to: '/experiences' });
+    }
+  }, [experience?._id, user?._id, status])
```
Comment (liadyacobi) [inline frontend/src/pages/experiences/experience-dialog/components/experience-dialog.tsx:48]:
```suggestion
  }, [experience?._id, user?._id, status]);
```

**Review by liadyacobi — APPROVED** [review]
